### ISSUE TITLE
Couldn't install

### ISSUE THREAD

**Issue by Bemmu** [hiquest/tvcl#6]
This might be the first time I tried to install something with npm, I probably just have a wrong version of something or the other, but anyway here's what happened after which I gave up.

    ~/b2/tests/anime_recommender bemmu$ sudo npm install tvcl -g
    Password:
    /usr/local/bin/tv -> /usr/local/lib/node_modules/tvcl/src/index.js
    npm WARN unmet dependency     /usr/local/lib/node_modules/meteorite/node_modules/prompt/node_modules/winston requires     colors@'0.x.x' but will load
    npm WARN unmet dependency /usr/local/lib/node_modules/meteorite/node_modules/colors,
    npm WARN unmet dependency which is version 0.6.0-1
    npm WARN unmet dependency /usr/local/lib/node_modules/npm/node_modules/npmconf requires     once@'~1.1.1' but will load
    npm WARN unmet dependency /usr/local/lib/node_modules/npm/node_modules/once,
    npm WARN unmet dependency which is version 1.3.3
    npm WARN unmet dependency /usr/local/lib/node_modules/npm/node_modules/npmconf requires     mkdirp@'~0.3.3' but will load
    npm WARN unmet dependency /usr/local/lib/node_modules/npm/node_modules/mkdirp,
    npm WARN unmet dependency which is version 0.5.1
    npm WARN unmet dependency /usr/local/lib/node_modules/npm/node_modules/npmconf requires     osenv@'0.0.3' but will load
    npm WARN unmet dependency /usr/local/lib/node_modules/npm/node_modules/osenv,
    npm WARN unmet dependency which is version 0.1.3
    npm WARN unmet dependency /usr/local/lib/node_modules/npm/node_modules/npmconf requires     nopt@'2' but will load
    npm WARN unmet dependency /usr/local/lib/node_modules/npm/node_modules/nopt,
    npm WARN unmet dependency which is version 3.0.6
    npm WARN unmet dependency /usr/local/lib/node_modules/npm/node_modules/npmconf requires     semver@'2' but will load
    npm WARN unmet dependency /usr/local/lib/node_modules/npm/node_modules/semver,
    npm WARN unmet dependency which is version 5.1.0
    npm WARN unmet dependency /usr/local/lib/node_modules/npm/node_modules/npmconf requires     ini@'~1.1.0' but will load
    npm WARN unmet dependency /usr/local/lib/node_modules/npm/node_modules/ini,
    npm WARN unmet dependency which is version 1.3.4
    npm WARN unmet dependency /usr/local/lib/node_modules/npm/node_modules/read-package-    json/node_modules/normalize-package-data requires semver@'2' but will load
    npm WARN unmet dependency /usr/local/lib/node_modules/npm/node_modules/semver,
    npm WARN unmet dependency which is version 5.1.0
    tvcl@1.0.8 /usr/local/lib/node_modules/tvcl
    ├── underscore@1.8.3
    ├── chalk@1.1.3 (supports-color@2.0.0, escape-string-regexp@1.0.5, ansi-styles@2.2.1, has-    ansi@2.0.0, strip-ansi@3.0.1)
    ├── rimraf@2.5.4 (glob@7.1.1)
    ├── unzip@0.1.11 (setimmediate@1.0.5, match-stream@0.0.2, pullstream@0.4.1, readable-    stream@1.0.34, binary@0.3.0, fstream@0.1.31)
    ├── request@2.79.0 (aws-sign2@0.6.0, tunnel-agent@0.4.3, oauth-sign@0.8.2, forever-agent@0    .6.1, is-typedarray@1.0.0, caseless@0.11.0, stringstream@0.0.5, aws4@1.5.0, isstream@0.1.    2, json-stringify-safe@5.0.1, extend@3.0.0, uuid@3.0.0, qs@6.3.0, combined-stream@1.0.5,     tough-cookie@2.3.2, mime-types@2.1.13, form-data@2.1.2, hawk@3.1.3, http-signature@1.1.1,     har-validator@2.0.6)
    ├── moment@2.17.0
    ├── xml2js@0.4.17 (sax@1.2.1, xmlbuilder@4.2.1)
    └── async@2.1.4 (lodash@4.17.2)
    (env)
    ~/b2/tests/anime_recommender bemmu$ tv
    /usr/local/lib/node_modules/tvcl/src/index.js:29
    let mod = commands.find((cmds) => {
    ^^^
    
    SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported     outside strict mode
        at exports.runInThisContext (vm.js:53:16)
        at Module._compile (module.js:373:25)
        at Object.Module._extensions..js (module.js:416:10)
        at Module.load (module.js:343:32)
        at Function.Module._load (module.js:300:12)
        at Function.Module.runMain (module.js:441:10)
        at startup (node.js:139:18)
        at node.js:974:3
    (env)
    ~/b2/tests/anime_recommender bemmu$

**Comment by hiquest** [comment]
@Bemmu what's your Node version?
