### ISSUE TITLE
RFC: Remove newline printing from `tv` and `tv remained` if no episodes are found 

### ISSUE THREAD

**Issue by lewiscowper** [hiquest/tvcl#7]
Hi! First of all, this is a really great program, and I love 99.999% of what you're doing with this. Really cool.

I have one tiny annoyance that I was wondering if you'd appreciate a pull request for, or would be happy to make yourself.

I'm currently running tv from my shell configuration file, so that if I have new TV shows to watch, I'll be alerted every time I open a terminal, in a message of the day style thing, however the script prints a newline when it doesn't find any episodes, (I believe the culprit is this line https://github.com/hiquest/tvcl/blob/master/src/cmd/remained.js#L32), and I was wondering if I could move that `pr("   ")` into the `if (eps.length)` block to get rid of (what I view as) undesired behaviour.

I understand it's completely because of my use case, and printing a blank line is useful to show that the command ran, and returned no new episodes, so if that's the case I'd be happy to fork and install from my own repo.

Hope you're doing well, and thanks very much.

**Comment by hiquest** [comment]
Thanks @lewiscowper ! That does make sense to me, and I will fix this when I get time (tomorrow probably)

**Comment by hiquest** [comment]
Hey @lewiscowper! Sorry, but after some thinking I decided I'd like to preserve the formatting (new lines)... I wonder if something like this would work for you (in wherever you use the script):

`tv lookup whatever | tr '\n' ' ` ?

You can even have it aliased:

`alias tv="tv $1 | tr '\n' ''"`
